version: '3.8'
services:
  nifi:
    image: apache/nifi:1.24.0
    container_name: nifi
    ports:
      - "8081:8080" 
    volumes:
      - ./nifi-data:/tmp/kafka-output
      - ./hadoop-conf:/opt/hadoop-conf

    environment:
      NIFI_WEB_HTTP_PORT: 8080
      SINGLE_USER_CREDENTIALS_USERNAME: amgad
      SINGLE_USER_CREDENTIALS_PASSWORD: amgad123
    networks:
      - bigdata_net

networks:
  bigdata_net:
    external: true
